[tools]
"aqua:miniscruff/changie" = "1.22.1"
"aqua:direnv/direnv" = "2.37.1"
"aqua:charmbracelet/glow" = "2.1.1"
"aqua:go-task/task" = "3.45.4"
"aqua:BurntSushi/ripgrep" = "15.1.0"
"aqua:volta-cli/volta" = "2.0.2"
"aqua:j178/prek" = "0.3.1"
hk = "latest"
pkl = "latest"
python = "3"
"aqua:koalaman/shellcheck" = "latest"
"aqua:rhysd/actionlint" = "latest"
"aqua:mvdan/sh" = "latest"                                  # shfmt
"aqua:google/yamlfmt" = "latest"
"aqua:crate-ci/typos" = "latest"
"aqua:editorconfig-checker/editorconfig-checker" = "latest"
"pipx:yamllint" = "latest"
bun = "latest"
"aqua:trufflesecurity/trufflehog" = "latest"
uv = "latest"
